Repository google-research/dex-lang, pull requests merged in 2021-01, with the labels that each got.

#405 clang install instructions
  README.md
Labels: cla: yes

#407 Add completions to REPL
  src/dex.hs
Labels: cla: yes

#432 Continue inlining after application
  src/lib/Embed.hs
  src/lib/Optimize.hs
Labels: cla: yes

#434 Fix the stupid zext bug
  src/lib/JIT.hs
  tests/show-tests.dx
Labels: cla: yes

#436 [README] Fix typo.
  README.md
Labels: cla: yes

#438 Use llvm-hs/llvm-hs@llvm-9 in cabal.project.
  cabal.project
Labels: cla: yes

#437 Gardening.
  .hlint.yaml
  benchmarks/dexbench.py
  dex.cabal
  makefile
  src/dex.hs
  src/lib/Actor.hs
  src/lib/Cat.hs
  src/lib/Imp.hs
  src/lib/LiveOutput.hs
  src/lib/Parser.hs
  src/lib/Syntax.hs
  src/lib/TopLevel.hs
Labels: cla: yes

#441 Fix `stack build` on macOS.
  dex.cabal
Labels: cla: yes

#442 Add `make watch` command for automatic rebuilding.
  makefile
Labels: cla: yes

#445 Remove extra CSS bottom padding in HTML-rendered Dex.
  static/style.css
Labels: cla: yes

#444 Add LaTeX rendering for HTML-rendered Dex via KaTeX.
  examples/latex.dx
  examples/pi.dx
  static/dynamic.js
  static/index.html
Labels: cla: yes

#446 Fix stack build warning for dex executable target.
  dex.cabal
Labels: cla: yes

#447 Do not perform `dex web` LaTeX rendering for non-prose blocks.
  examples/latex.dx
  static/dynamic.js
Labels: cla: yes, tooling / notebooks

#452 Some QoL functions for the Prelude
  lib/prelude.dx
Labels: cla: yes

#453 NFC: rename `List` ADT field.
  lib/prelude.dx
Labels: cla: yes

#455 Add Ord instance for tables.
  lib/prelude.dx
  tests/type-tests.dx
Labels: cla: yes

#468 Break prelude up into sections
  lib/prelude.dx
Labels: cla: yes

#461 [NFC] Rename "Embed" to "Builder".
  dex.cabal
  src/lib/Algebra.hs
  src/lib/Autodiff.hs
  src/lib/Builder.hs
  src/lib/Export.hs
  src/lib/Imp.hs
  src/lib/Imp/Builder.hs
  src/lib/Imp/Optimize.hs
  src/lib/Inference.hs
  src/lib/Interpreter.hs
  src/lib/Optimize.hs
  src/lib/Parallelize.hs
  src/lib/Simplify.hs
  src/lib/Syntax.hs
  src/lib/TopLevel.hs
Labels: cla: yes, maintenance

#443 Dex Tutorial
  examples/tutorial.dx
Labels: cla: yes

#456 NN / MNist Example
  examples/nn.dx
Labels: cla: yes

#485 Added Eq instance and Monoid helper for Lists, and a filter function.
  examples/particle-filter.dx
  lib/prelude.dx
  tests/monad-tests.dx
Labels: cla: yes
